use anyhow::Result;
use handlebars::Handlebars;
use serde::Serialize;
use std::fs::File;
use std::io::Write;
use tracing::info;

use crate::models::{ScanResult, Severity};

#[derive(Default, Clone)]
pub struct ReportGenerator {
    hb: Handlebars<'static>,
}

impl ReportGenerator {
    pub fn new() -> Self {
        let mut hb = Handlebars::new();
        hb.register_template_string("report", TEMPLATE)
            .expect("template compiles");
        Self { hb }
    }

    pub fn generate_html_report(&self, scan_result: &ScanResult, output_path: &str) -> Result<()> {
        let context = ReportContext::from_result(scan_result);
        let html = self.hb.render("report", &context)?;
        let mut file = File::create(output_path)?;
        file.write_all(html.as_bytes())?;
        info!("report written to {output_path}");
        Ok(())
    }

    pub fn generate_json_report(&self, scan_result: &ScanResult, output_path: &str) -> Result<()> {
        let json = serde_json::to_string_pretty(scan_result)?;
        let mut file = File::create(output_path)?;
        file.write_all(json.as_bytes())?;
        info!("json report written to {output_path}");
        Ok(())
    }
}

#[derive(Serialize)]
struct ReportContext<'a> {
    scan: &'a ScanResult,
    summary: SeveritySummary,
    total_findings: usize,
}

#[derive(Serialize, Default)]
struct SeveritySummary {
    critical: usize,
    high: usize,
    medium: usize,
    low: usize,
    info: usize,
}

impl<'a> ReportContext<'a> {
    fn from_result(scan: &'a ScanResult) -> Self {
        let mut summary = SeveritySummary::default();
        for finding in &scan.findings {
            match finding.severity {
                Severity::Critical => summary.critical += 1,
                Severity::High => summary.high += 1,
                Severity::Medium => summary.medium += 1,
                Severity::Low => summary.low += 1,
                Severity::Info => summary.info += 1,
            }
        }
        Self {
            scan,
            summary,
            total_findings: scan.findings.len(),
        }
    }
}

const TEMPLATE: &str = r#"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Khepri Scan Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 32px; background: #0f172a; color: #e2e8f0; }
    h1 { color: #c084fc; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th, td { border: 1px solid #1f2937; padding: 8px; }
    th { background: #111827; }
    tr:nth-child(even) { background: #1f2937; }
    .pill { padding: 4px 8px; border-radius: 8px; color: #0f172a; }
    .critical { background: #f97316; }
    .high { background: #facc15; }
    .medium { background: #22d3ee; }
    .low { background: #a3e635; }
    .info { background: #cbd5e1; }
  </style>
</head>
<body>
  <h1>🔮 Khepri Scan Report</h1>
  <p><strong>Scan ID:</strong> {{scan.id}}<br/>
     <strong>Target ID:</strong> {{scan.target_id}}<br/>
     <strong>Started:</strong> {{scan.started_at}}<br/>
     <strong>Ended:</strong> {{scan.ended_at}}</p>

  <h2>Summary</h2>
  <ul>
    <li>Total findings: {{total_findings}}</li>
    <li>Critical: {{summary.critical}} | High: {{summary.high}} | Medium: {{summary.medium}} | Low: {{summary.low}} | Info: {{summary.info}}</li>
    <li>Total subdomains: {{scan.total_subdomains_discovered}}</li>
    <li>Total endpoints probed: {{scan.total_endpoints_probed}}</li>
  </ul>

  <h2>Findings</h2>
  <table>
    <thead>
      <tr>
        <th>Severity</th>
        <th>Type</th>
        <th>Endpoint</th>
        <th>Evidence</th>
        <th>Tool</th>
        <th>Verified</th>
      </tr>
    </thead>
    <tbody>
      {{#each scan.findings}}
      <tr>
        <td><span class="pill {{severity}}">{{severity}}</span></td>
        <td>{{vulnerability_type}}</td>
        <td>{{endpoint}}</td>
        <td>{{evidence}}</td>
        <td>{{tool_source}}</td>
        <td>{{verified}}</td>
      </tr>
      {{/each}}
    </tbody>
  </table>
  <p style="margin-top:32px; color:#94a3b8;">Generated by Khepri.</p>
</body>
</html>
"#;
